# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76e57a5632c0cafa748651043f55df5fd768b24880217ed0a0df2966de8bd9388083b50190b5fd4226c565cdc064b2e26c549460d33d4235edc6dd3549bef5bf

test:
  secret_key_base: 00029d64d6ba25b2556b121a22eeac23fd7e8dbcc2c59dad7154d87dcf46e5961d3123b12dacface43c5d0875bccac20d1d25c525755f612e1fdbfb1c72e8d16

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
